/mvp2_test_robot/reporter_c2_serial_comm:
  ros__parameters:
    port: /dev/ttyUSB1
    baudrate: 115200

/mvp2_test_robot/mvp_c2_reporter:
  ros__parameters:
    dccl_tx_interval: 1.0
    helm_state_list: ['start', 'kill', 'survey', 'profiling', 'teleop']
    launch_packages: ['mvp2_test_robot_bringup', 'mvp2_test_robot_bringup']
    launch_files: ['bringup_simulation', 'bringup_test']