/mvp2_test_robot/imu_driver_node:
    ros__parameters:
      roll_offset: 3.1415926
      pitch_offset: 0.0
      yaw_offset: 1.5707
      roll_reverse: 1.0
      pitch_reverse: -1.0
      yaw_reverse: -1.0

/mvp2_test_robot/thruster_driver_node:
    ros__parameters:
      thruster_pub_topic: /mvp2_test_robot/stonefish/thruster_command
      thruster_length: 4
      thruster_sub_topics: [/mvp2_test_robot/control/thruster/surge, 
                          /mvp2_test_robot/control/thruster/sway_bow, 
                          /mvp2_test_robot/control/thruster/heave_stern, 
                          /mvp2_test_robot/control/thruster/heave_bow]

/mvp2_test_robot/servo_driver_node:
    ros__parameters:
      servo_pub_topic: /mvp2_test_robot/fins/desired_joint_states
      servo_length: 1
      servo_sub_topics: [/mvp2_test_robot/control/fin/rudder]
      servo_joint_names: [mvp2_test_robot/rudder_joint]

/mvp2_test_robot/dvl_driver_node:
    ros__parameters:
      dvl_in: /mvp2_test_robot/dvl/stonefish/raw
      dvl_out: /mvp2_test_robot/dvl/twist